### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by EpicBoredPerson** [ZapCloud/Festivities3#1]
I downloaded the mod and it keeps crashing when I go to use it.

**Comment by samsartor** [comment]
More info please

**Comment by yopo** [comment]
it keeps crashing pls help i downloaded the installer only cause thats  the only download i found heres the crash report---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 12/23/14 7:16 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at net.minecraft.client.network.NetHandlerPlayClient.func_147281_a(NetHandlerPlayClient.java:744)
    at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:97)
    at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:15)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2050)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.client.network.NetHandlerPlayClient.func_147281_a(NetHandlerPlayClient.java:744)
    at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:97)
    at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:15)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Kaisnakepit'/483, l='MpServer', x=224.50, y=71.62, z=243.50]]
    Chunk stats: MultiplayerChunkCache: 25, 25
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (220,64,248), Chunk: (at 12,4,8 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 55 game time, 55 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 54 total; [EntityZombie['Zombie'/522, l='MpServer', x=234.50, y=21.00, z=224.50], EntitySkeleton['Skeleton'/524, l='MpServer', x=230.50, y=21.00, z=226.50], EntitySkeleton['Skeleton'/525, l='MpServer', x=228.50, y=21.00, z=227.50], EntityZombie['Zombie'/287, l='MpServer', x=208.50, y=22.00, z=231.50], EntityZombie['Zombie'/288, l='MpServer', x=222.50, y=33.00, z=227.50], EntitySkeleton['Skeleton'/289, l='MpServer', x=216.50, y=33.00, z=226.50], EntitySkeleton['Skeleton'/290, l='MpServer', x=208.50, y=31.41, z=224.50], EntityBat['Bat'/295, l='MpServer', x=228.59, y=23.56, z=240.84], EntityZombie['Zombie'/296, l='MpServer', x=230.50, y=13.00, z=259.50], EntityZombie['Zombie'/297, l='MpServer', x=232.50, y=13.00, z=259.50], EntitySkeleton['Skeleton'/298, l='MpServer', x=238.50, y=14.00, z=269.50], EntityZombie['Zombie'/299, l='MpServer', x=224.50, y=29.00, z=283.50], EntityZombie['Zombie'/300, l='MpServer', x=225.50, y=29.00, z=283.50], EntitySkeleton['Skeleton'/322, l='MpServer', x=243.50, y=25.00, z=224.50], EntitySheep['Sheep'/323, l='MpServer', x=250.91, y=63.00, z=226.50], EntitySheep['Sheep'/324, l='MpServer', x=252.81, y=63.00, z=227.53], EntitySheep['Sheep'/325, l='MpServer', x=251.50, y=63.00, z=229.50], EntitySheep['Sheep'/326, l='MpServer', x=252.81, y=64.00, z=225.47], EntityClientPlayerMP['Kaisnakepit'/483, l='MpServer', x=224.50, y=71.62, z=243.50], EntityFallingBlock['Falling Block'/471, l='MpServer', x=211.50, y=30.41, z=225.50], EntityFallingBlock['Falling Block'/472, l='MpServer', x=212.50, y=31.41, z=225.50], EntityFallingBlock['Falling Block'/473, l='MpServer', x=210.50, y=31.41, z=224.50], EntityBat['Bat'/217, l='MpServer', x=204.06, y=16.19, z=221.69], EntityFallingBlock['Falling Block'/474, l='MpServer', x=211.50, y=31.41, z=224.50], EntityBat['Bat'/218, l='MpServer', x=202.09, y=16.44, z=223.94], EntityFallingBlock['Falling Block'/475, l='MpServer', x=209.50, y=31.41, z=224.50], EntitySkeleton['Skeleton'/219, l='MpServer', x=201.50, y=33.00, z=218.50], EntityFallingBlock['Falling Block'/476, l='MpServer', x=213.50, y=31.41, z=225.50], EntityFallingBlock['Falling Block'/220, l='MpServer', x=207.50, y=40.13, z=221.50], EntityFallingBlock['Falling Block'/477, l='MpServer', x=208.50, y=31.41, z=224.50], EntityFallingBlock['Falling Block'/221, l='MpServer', x=207.50, y=40.13, z=222.50], EntityFallingBlock['Falling Block'/478, l='MpServer', x=220.50, y=43.41, z=226.50], EntityFallingBlock['Falling Block'/222, l='MpServer', x=207.50, y=40.13, z=223.50], EntityFallingBlock['Falling Block'/479, l='MpServer', x=220.50, y=43.66, z=225.50], EntityFallingBlock['Falling Block'/223, l='MpServer', x=206.50, y=40.13, z=221.50], EntityFallingBlock['Falling Block'/480, l='MpServer', x=215.50, y=19.91, z=271.50], EntityFallingBlock['Falling Block'/224, l='MpServer', x=206.50, y=40.13, z=222.50], EntityFallingBlock['Falling Block'/225, l='MpServer', x=206.50, y=40.13, z=223.50], EntityFallingBlock['Falling Block'/226, l='MpServer', x=207.50, y=40.13, z=220.50], EntityFallingBlock['Falling Block'/227, l='MpServer', x=205.50, y=40.13, z=220.50], EntityFallingBlock['Falling Block'/484, l='MpServer', x=250.50, y=12.09, z=230.50], EntityFallingBlock['Falling Block'/228, l='MpServer', x=205.50, y=40.13, z=221.50], EntityFallingBlock['Falling Block'/229, l='MpServer', x=205.50, y=40.13, z=222.50], EntityFallingBlock['Falling Block'/230, l='MpServer', x=206.50, y=40.13, z=220.50], EntityFallingBlock['Falling Block'/231, l='MpServer', x=204.50, y=40.13, z=220.50], EntityFallingBlock['Falling Block'/232, l='MpServer', x=204.50, y=40.13, z=221.50], EntityBat['Bat'/233, l='MpServer', x=202.78, y=17.03, z=229.47], EntityBat['Bat'/234, l='MpServer', x=202.69, y=16.44, z=227.75], EntityZombie['Zombie'/235, l='MpServer', x=202.50, y=28.00, z=275.50], EntityZombie['Zombie'/236, l='MpServer', x=206.50, y=28.00, z=275.50], EntityCow['Cow'/237, l='MpServer', x=200.50, y=66.00, z=283.78], EntityCow['Cow'/238, l='MpServer', x=200.50, y=67.00, z=287.81], EntityCow['Cow'/239, l='MpServer', x=200.50, y=66.00, z=286.41], EntityCow['Cow'/240, l='MpServer', x=200.50, y=66.00, z=285.06]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 212477488 bytes (202 MB) / 366841856 bytes (349 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 7 mods loaded, 7 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1230} [Forge Mod Loader](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1230} [Minecraft Forge](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TooManyItems{1.7.10} [TooManyItems](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ReiMinimap{1.7.10} [Rei's Minimap](ReiMinimap-1.7.10-3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TooMuchTNT{2.9} [TooMuchTNT](TooMuchTNT v2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Wintercraft{1.1.1} [Wintercraft](Wintercraft-1.7.10-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.7.10-Forge10.13.2.1230
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Gra
